<div id="container" class="">
    <p class="text-4xl font-bold text-center mb-8 pt-8">
        Heatmap of Variable Correlations
    </p>
</div>

<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-core.min.js"></script>
<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-heatmap.min.js"></script>

<script>
  anychart.onDocumentReady(function () {

    // create the data
    var data = [
        { x: "Ville_id", y: "Ville_id", heat: 1 },
        { x: "sex", y: "Ville_id", heat: 0.0065 },
        { x: "Age", y: "Ville_id", heat: -0.015 },
        { x: "Married", y: "Ville_id", heat: 0.027 },
        { x: "Number_children", y: "Ville_id", heat: 0.028 },
        { x: "education_level", y: "Ville_id", heat: -0.01 },
        { x: "total_members", y: "Ville_id", heat: 0.004 },
        { x: "gained_asset", y: "Ville_id", heat: -0.016 },
        { x: "durable_asset", y: "Ville_id", heat: -0.026 },
        { x: "save_asset", y: "Ville_id", heat: -0.019 },
        { x: "living_expenses", y: "Ville_id", heat: -0.027 },
        { x: "other_expenses", y: "Ville_id", heat: 0.005 },
        { x: "incoming_salary", y: "Ville_id", heat: -0.015 },
        { x: "incoming_own_farm", y: "Ville_id", heat: -0.1 },
        { x: "incoming_business", y: "Ville_id", heat: -0.014 },
        { x: "incoming_no_business", y: "Ville_id", heat: -0.019 },
        { x: "incoming_agricultural", y: "Ville_id", heat: 0.018 },
        { x: "farm_expenses", y: "Ville_id", heat: 0.058 },
        { x: "labor_primary", y: "Ville_id", heat: -0.029 },
        { x: "lasting_investment", y: "Ville_id", heat: -0.041 },
        { x: "no_lasting_investmen", y: "Ville_id", heat: 0.0044 },
        { x: "depressed", y: "Ville_id", heat: 0.028 },

        { x: "Ville_id", y: "sex", heat: 0.0065 },
        { x: "sex", y: "sex", heat: 1 },
        { x: "Age", y: "sex", heat: -0.16 },
        { x: "Married", y: "sex", heat: 0.28 },
        { x: "Number_children", y: "sex", heat: 0.21 },
        { x: "education_level", y: "sex", heat: -0.075 },
        { x: "total_members", y: "sex", heat: 0.18 },
        { x: "gained_asset", y: "sex", heat: 0.021 },
        { x: "durable_asset", y: "sex", heat: 0.031 },
        { x: "save_asset", y: "sex", heat: 0.0059 },
        { x: "living_expenses", y: "sex", heat: 0.0041 },
        { x: "other_expenses", y: "sex", heat: 0.055 },
        { x: "incoming_salary", y: "sex", heat: -0.039 },
        { x: "incoming_own_farm", y: "sex", heat: 0.067 },
        { x: "incoming_business", y: "sex", heat: 0.088 },
        { x: "incoming_no_business", y: "sex", heat: 0.1 },
        { x: "incoming_agricultural", y: "sex", heat: 0.018 },
        { x: "farm_expenses", y: "sex", heat: 0.071 },
        { x: "labor_primary", y: "sex", heat: -0.031 },
        { x: "lasting_investment", y: "sex", heat: 0.041 },
        { x: "no_lasting_investmen", y: "sex", heat: 0.048 },
        { x: "depressed", y: "sex", heat: -0.0057 },

        { x: "Ville_id", y: "Age", heat: -0.015 },
        { x: "sex", y: "Age", heat: -0.16 },
        { x: "Age", y: "Age", heat: 1 },
        { x: "Married", y: "Age", heat: -0.39 },
        { x: "Number_children", y: "Age", heat: -0.13 },
        { x: "education_level", y: "Age", heat: -0.37 },
        { x: "total_members", y: "Age", heat: -0.065 },
        { x: "gained_asset", y: "Age", heat: 0.0031 },
        { x: "durable_asset", y: "Age", heat:0.045 },
        { x: "save_asset", y: "Age", heat: -0.023 },
        { x: "living_expenses", y: "Age", heat: -0.031 },
        { x: "other_expenses", y: "Age", heat: 0.02 },
        { x: "incoming_salary", y: "Age", heat: -0.045 },
        { x: "incoming_own_farm", y: "Age", heat: 0.13 },
        { x: "incoming_business", y: "Age", heat: -0.028 },
        { x: "incoming_no_business", y: "Age", heat: -0.087 },
        { x: "incoming_agricultural", y: "Age", heat: -0.0087 },
        { x: "farm_expenses", y: "Age", heat: -0.009 },
        { x: "labor_primary", y: "Age", heat: -0.056 },
        { x: "lasting_investment", y: "Age", heat: 0.043 },
        { x: "no_lasting_investmen", y: "Age", heat: -0.023},
        { x: "depressed", y: "Age", heat: 0.1 },

        { x: "Ville_id", y: "Married", heat: 0.027 },
        { x: "sex", y: "Married", heat: 0.28 },
        { x: "Age", y: "Married", heat: -0.39 },
        { x: "Married", y: "Married", heat: 1 },
        { x: "Number_children", y: "Married", heat: 0.22 },
        { x: "education_level", y: "Married", heat: 0.21 },
        { x: "total_members", y: "Married", heat: 0.24 },
        { x: "gained_asset", y: "Married", heat: -0.015 },
        { x: "durable_asset", y: "Married", heat: -0.044 },
        { x: "save_asset", y: "Married", heat: 0.0059 },
        { x: "living_expenses", y: "Married", heat: 0.022 },
        { x: "other_expenses", y: "Married", heat: 0.031 },
        { x: "incoming_salary", y: "Married", heat: 0.013 },
        { x: "incoming_own_farm", y: "Married", heat: 0.0031 },
        { x: "incoming_business", y: "Married", heat: -0.034 },
        { x: "incoming_no_business", y: "Married", heat: 0.042 },
        { x: "incoming_agricultural", y: "Married", heat: -0.044 },
        { x: "farm_expenses", y: "Married", heat: 0.36 },
        { x: "labor_primary", y: "Married", heat: 0.0066 },
        { x: "lasting_investment", y: "Married", heat: 0.0035 },
        { x: "no_lasting_investmen", y: "Married", heat: 0.05},
        { x: "depressed", y: "Married", heat: -0.064 },

        { x: "Ville_id", y: "Number_children", heat: 0.028 },
        { x: "sex", y: "Number_children", heat: 0.21 },
        { x: "Age", y: "Number_children", heat: -0.13 },
        { x: "Married", y: "Number_children", heat: 0.22 },
        { x: "Number_children", y: "Number_children", heat: 1 },
        { x: "education_level", y: "Number_children", heat: 0.17 },
        { x: "total_members", y: "Number_children", heat: 0.78 },
        { x: "gained_asset", y: "Number_children", heat: 0.02 },
        { x: "durable_asset", y: "Number_children", heat: -0.0076 },
        { x: "save_asset", y: "Number_children", heat: 0.027 },
        { x: "living_expenses", y: "Number_children", heat: -0.001 },
        { x: "other_expenses", y: "Number_children", heat: 0.0053 },
        { x: "incoming_salary", y: "Number_children", heat: -0.015 },
        { x: "incoming_own_farm", y: "Number_children", heat: 0.058 },
        { x: "incoming_business", y: "Number_children", heat: 0.029 },
        { x: "incoming_no_business", y: "Number_children", heat: 0.06 },
        { x: "incoming_agricultural", y: "Number_children", heat: -0.016 },
        { x: "farm_expenses", y: "Number_children", heat: 0.05 },
        { x: "labor_primary", y: "Number_children", heat: -0.014 },
        { x: "lasting_investment", y: "Number_children", heat: 0.044 },
        { x: "no_lasting_investmen", y: "Number_children", heat: 0.014},
        { x: "depressed", y: "Number_children", heat: 0.0034 },

        { x: "Ville_id", y: "education_level", heat: -0.01 },
        { x: "sex", y: "education_level", heat: -0.075 },
        { x: "Age", y: "education_level", heat: -0.37 },
        { x: "Married", y: "education_level", heat: 0.21 },
        { x: "Number_children", y: "education_level", heat: 0.17 },
        { x: "education_level", y: "education_level", heat: 1 },
        { x: "total_members", y: "education_level", heat: 0.12 },
        { x: "gained_asset", y: "education_level", heat: 0.018 },
        { x: "durable_asset", y: "education_level", heat: -0.011 },
        { x: "save_asset", y: "education_level", heat: 0.045 },
        { x: "living_expenses", y: "education_level", heat: 0.01 },
        { x: "other_expenses", y: "education_level", heat: -0.039 },
        { x: "incoming_salary", y: "education_level", heat: 0.0083 },
        { x: "incoming_own_farm", y: "education_level", heat: -0.036 },
        { x: "incoming_business", y: "education_level", heat: 0.013 },
        { x: "incoming_no_business", y: "education_level", heat: 0.036 },
        { x: "incoming_agricultural", y: "education_level", heat: -0.056 },
        { x: "farm_expenses", y: "education_level", heat: 0.01 },
        { x: "labor_primary", y: "education_level", heat: 0.04 },
        { x: "lasting_investment", y: "education_level", heat: 0.0031 },
        { x: "no_lasting_investmen", y: "education_level", heat: 0.014},
        { x: "depressed", y: "education_level", heat: -0.097 },

        { x: "Ville_id", y: "total_members", heat: 0.004 },
        { x: "sex", y: "total_members", heat: 0.18 },
        { x: "Age", y: "total_members", heat: -0.065 },
        { x: "Married", y: "total_members", heat: 0.24 },
        { x: "Number_children", y: "total_members", heat: 0.78 },
        { x: "education_level", y: "total_members", heat: 0.12 },
        { x: "total_members", y: "total_members", heat: 1 },
        { x: "gained_asset", y: "total_members", heat: 0.02 },
        { x: "durable_asset", y: "total_members", heat: -0.032 },
        { x: "save_asset", y: "total_members", heat: 0.036 },
        { x: "living_expenses", y: "total_members", heat: -0.0059 },
        { x: "other_expenses", y: "total_members", heat: 0.012 },
        { x: "incoming_salary", y: "total_members", heat: -0.042 },
        { x: "incoming_own_farm", y: "total_members", heat: 0.088 },
        { x: "incoming_business", y: "total_members", heat: 0.0033 },
        { x: "incoming_no_business", y: "total_members", heat: 0.063 },
        { x: "incoming_agricultural", y: "total_members", heat: 0.023 },
        { x: "farm_expenses", y: "total_members", heat: 0.071 },
        { x: "labor_primary", y: "total_members", heat: -0.04 },
        { x: "lasting_investment", y: "total_members", heat: 0.046 },
        { x: "no_lasting_investmen", y: "total_members", heat: 0.48},
        { x: "depressed", y: "total_members", heat: 0.033 },

        { x: "Ville_id", y: "gained_asset", heat: -0.016 },
        { x: "sex", y: "gained_asset", heat: 0.021 },
        { x: "Age", y: "gained_asset", heat: 0.0031 },
        { x: "Married", y: "gained_asset", heat: -0.015 },
        { x: "Number_children", y: "gained_asset", heat: 0.02 },
        { x: "education_level", y: "gained_asset", heat: 0.018 },
        { x: "total_members", y: "gained_asset", heat: 0.02 },
        { x: "gained_asset", y: "gained_asset", heat: 1 },
        { x: "durable_asset", y: "gained_asset", heat: -0.0064 },
        { x: "save_asset", y: "gained_asset", heat: 0.0021 },
        { x: "living_expenses", y: "gained_asset", heat: 0.076 },
        { x: "other_expenses", y: "gained_asset", heat: 0.033 },
        { x: "incoming_salary", y: "gained_asset", heat: 0.031 },
        { x: "incoming_own_farm", y: "gained_asset", heat: 0.12 },
        { x: "incoming_business", y: "gained_asset", heat: 0.051 },
        { x: "incoming_no_business", y: "gained_asset", heat: 0.077 },
        { x: "incoming_agricultural", y: "gained_asset", heat: 0.029 },
        { x: "farm_expenses", y: "gained_asset", heat: 0.059 },
        { x: "labor_primary", y: "gained_asset", heat: 0.025 },
        { x: "lasting_investment", y: "gained_asset", heat: 0.032 },
        { x: "no_lasting_investmen", y: "gained_asset", heat: 0.031},
        { x: "depressed", y: "gained_asset", heat: -0.0051 },

        { x: "Ville_id", y: "durable_asset", heat: -0.026 },
        { x: "sex", y: "durable_asset", heat: 0.031 },
        { x: "Age", y: "durable_asset", heat: 0.045 },
        { x: "Married", y: "durable_asset", heat: -0.044 },
        { x: "Number_children", y: "durable_asset", heat: -0.0076 },
        { x: "education_level", y: "durable_asset", heat: -0.011 },
        { x: "total_members", y: "durable_asset", heat: -0.032 },
        { x: "gained_asset", y: "durable_asset", heat: -0.0064},
        { x: "durable_asset", y: "durable_asset", heat: 1 },
        { x: "save_asset", y: "durable_asset", heat: -0.037 },
        { x: "living_expenses", y: "durable_asset", heat: 0.026 },
        { x: "other_expenses", y: "durable_asset", heat: 0.078 },
        { x: "incoming_salary", y: "durable_asset", heat: 0.075 },
        { x: "incoming_own_farm", y: "durable_asset", heat: 0.07 },
        { x: "incoming_business", y: "durable_asset", heat: 0.018 },
        { x: "incoming_no_business", y: "durable_asset", heat: 0.024 },
        { x: "incoming_agricultural", y: "durable_asset", heat: 0.026 },
        { x: "farm_expenses", y: "durable_asset", heat: 0.029 },
        { x: "labor_primary", y: "durable_asset", heat: 0.09 },
        { x: "lasting_investment", y: "durable_asset", heat: 0.25 },
        { x: "no_lasting_investmen", y: "durable_asset", heat: 0.022},
        { x: "depressed", y: "durable_asset", heat: 0.038 },

        { x: "Ville_id", y: "save_asset", heat: -0.019 },
        { x: "sex", y: "save_asset", heat: 0.0059 },
        { x: "Age", y: "save_asset", heat: -0.023 },
        { x: "Married", y: "save_asset", heat: 0.0059 },
        { x: "Number_children", y: "save_asset", heat: 0.027 },
        { x: "education_level", y: "save_asset", heat: 0.045 },
        { x: "total_members", y: "save_asset", heat: 0.036 },
        { x: "gained_asset", y: "save_asset", heat: -0.0021},
        { x: "durable_asset", y: "save_asset", heat: -0.037 },
        { x: "save_asset", y: "save_asset", heat: 1 },
        { x: "living_expenses", y: "save_asset", heat: 0.026 },
        { x: "other_expenses", y: "save_asset", heat: 0.034 },
        { x: "incoming_salary", y: "save_asset", heat: 0.044 },
        { x: "incoming_own_farm", y: "save_asset", heat: 0.039 },
        { x: "incoming_business", y: "save_asset", heat: 0.067 },
        { x: "incoming_no_business", y: "save_asset", heat: 0.054 },
        { x: "incoming_agricultural", y: "save_asset", heat: 0.023 },
        { x: "farm_expenses", y: "save_asset", heat: 0.04 },
        { x: "labor_primary", y: "save_asset", heat: 0.067 },
        { x: "lasting_investment", y: "save_asset", heat: 0.039 },
        { x: "no_lasting_investmen", y: "save_asset", heat: 0.029},
        { x: "depressed", y: "save_asset", heat: 0.011 },

        { x: "Ville_id", y: "living_expenses", heat: -0.027 },
        { x: "sex", y: "living_expenses", heat: -0.0041 },
        { x: "Age", y: "living_expenses", heat: -0.031 },
        { x: "Married", y: "living_expenses", heat: 0.022 },
        { x: "Number_children", y: "living_expenses", heat: -0.001 },
        { x: "education_level", y: "living_expenses", heat: 0.01 },
        { x: "total_members", y: "living_expenses", heat: -0.0059 },
        { x: "gained_asset", y: "living_expenses", heat: 0.076},
        { x: "durable_asset", y: "living_expenses", heat: 0.026 },
        { x: "save_asset", y: "living_expenses", heat: 0.026 },
        { x: "living_expenses", y: "living_expenses", heat: 1 },
        { x: "other_expenses", y: "living_expenses", heat: 0.062 },
        { x: "incoming_salary", y: "living_expenses", heat: 0.086 },
        { x: "incoming_own_farm", y: "living_expenses", heat: 0.077 },
        { x: "incoming_business", y: "living_expenses", heat: 0.032 },
        { x: "incoming_no_business", y: "living_expenses", heat: 0.024 },
        { x: "incoming_agricultural", y: "living_expenses", heat: 0.12 },
        { x: "farm_expenses", y: "living_expenses", heat: 0.0035 },
        { x: "labor_primary", y: "living_expenses", heat: 0.08 },
        { x: "lasting_investment", y: "living_expenses", heat: 0.04 },
        { x: "no_lasting_investmen", y: "living_expenses", heat: 0.047},
        { x: "depressed", y: "living_expenses", heat: -0.024 },

        { x: "Ville_id", y: "other_expenses", heat: 0.005 },
        { x: "sex", y: "other_expenses", heat: 0.055 },
        { x: "Age", y: "other_expenses", heat: 0.02 },
        { x: "Married", y: "other_expenses", heat: 0.031 },
        { x: "Number_children", y: "other_expenses", heat: 0.0053 },
        { x: "education_level", y: "other_expenses", heat: -0.039 },
        { x: "total_members", y: "other_expenses", heat: 0.012 },
        { x: "gained_asset", y: "other_expenses", heat: 0.033},
        { x: "durable_asset", y: "other_expenses", heat: 0.078 },
        { x: "save_asset", y: "other_expenses", heat: 0.034 },
        { x: "living_expenses", y: "other_expenses", heat: 0.062 },
        { x: "other_expenses", y: "other_expenses", heat: 1 },
        { x: "incoming_salary", y: "other_expenses", heat: 0.043 },
        { x: "incoming_own_farm", y: "other_expenses", heat: 0.06 },
        { x: "incoming_business", y: "other_expenses", heat: 0.01 },
        { x: "incoming_no_business", y: "other_expenses", heat: 0.075 },
        { x: "incoming_agricultural", y: "other_expenses", heat: 0.073 },
        { x: "farm_expenses", y: "other_expenses", heat: 0.043 },
        { x: "labor_primary", y: "other_expenses", heat: 0.052 },
        { x: "lasting_investment", y: "other_expenses", heat: 0.047 },
        { x: "no_lasting_investmen", y: "other_expenses", heat: 0.019},
        { x: "depressed", y: "other_expenses", heat: -0.011 },

        { x: "Ville_id", y: "incoming_salary", heat: -0.015 },
        { x: "Ville_id", y: "incoming_own_farm", heat: 0.1 },
        { x: "Ville_id", y: "incoming_business", heat: -0.014 },
        { x: "Ville_id", y: "incoming_no_business", heat: -0.019 },
        { x: "Ville_id", y: "incoming_agricultural", heat: 0.018 },
        { x: "Ville_id", y: "farm_expenses", heat: 0.058 },
        { x: "Ville_id", y: "labor_primary", heat: -0.029 },
        { x: "Ville_id", y: "lasting_investment", heat: -0.041 },
        { x: "Ville_id", y: "no_lasting_investmen", heat: 0.0044 },
        { x: "Ville_id", y: "depressed", heat: 0.028 },
        { x: "sex", y: "incoming_salary", heat: -0.039 },
        { x: "sex", y: "incoming_own_farm", heat: 0.067 },
        { x: "sex", y: "incoming_business", heat: 0.088 },
        { x: "sex", y: "incoming_no_business", heat: 0.1 },
        { x: "sex", y: "incoming_agricultural", heat: 0.018 },
        { x: "sex", y: "farm_expenses", heat: 0.071 },
        { x: "sex", y: "labor_primary", heat: -0.031 },
        { x: "sex", y: "lasting_investment", heat: 0.041 },
        { x: "sex", y: "no_lasting_investmen", heat: 0.048 },
        { x: "sex", y: "depressed", heat: 0.0057 },
        { x: "Age", y: "incoming_salary", heat: -0.045 },
        { x: "Age", y: "incoming_own_farm", heat: 0.13 },
        { x: "Age", y: "incoming_business", heat: -0.028 },
        { x: "Age", y: "incoming_no_business", heat: -0.087 },
        { x: "Age", y: "incoming_agricultural", heat: -0.0087 },
        { x: "Age", y: "farm_expenses", heat: -0.009 },
        { x: "Age", y: "labor_primary", heat: -0.056 },
        { x: "Age", y: "lasting_investment", heat: 0.043 },
        { x: "Age", y: "no_lasting_investmen", heat: -0.023 },
        { x: "Age", y: "depressed", heat: 0.1 },
        { x: "Married", y: "incoming_salary", heat: 0.013 },
        { x: "Married", y: "incoming_own_farm", heat: 0.0031 },
        { x: "Married", y: "incoming_business", heat: -0.034 },
        { x: "Married", y: "incoming_no_business", heat: 0.042 },
        { x: "Married", y: "incoming_agricultural", heat: -0.044 },
        { x: "Married", y: "farm_expenses", heat: 0.036 },
        { x: "Married", y: "labor_primary", heat: 0.0066 },
        { x: "Married", y: "lasting_investment", heat: 0.0035 },
        { x: "Married", y: "no_lasting_investmen", heat: 0.05 },
        { x: "Married", y: "depressed", heat: -0.064 },
        { x: "Number_children", y: "incoming_salary", heat: -0.015 },
        { x: "Number_children", y: "incoming_own_farm", heat: 0.058 },
        { x: "Number_children", y: "incoming_business", heat: 0.029 },
        { x: "Number_children", y: "incoming_no_business", heat: 0.06 },
        { x: "Number_children", y: "incoming_agricultural", heat: 0.016 },
        { x: "Number_children", y: "farm_expenses", heat: 0.05 },
        { x: "Number_children", y: "labor_primary", heat: -0.014 },
        { x: "Number_children", y: "lasting_investment", heat: 0.044 },
        { x: "Number_children", y: "no_lasting_investmen", heat: 0.014 },
        { x: "Number_children", y: "depressed", heat: 0.0034 },
        { x: "education_level", y: "incoming_salary", heat: 0.0083 },
        { x: "education_level", y: "incoming_own_farm", heat: -0.036 },
        { x: "education_level", y: "incoming_business", heat: 0.013 },
        { x: "education_level", y: "incoming_no_business", heat: 0.036 },
        { x: "education_level", y: "incoming_agricultural", heat: -0.056 },
        { x: "education_level", y: "farm_expenses", heat: 0.01 },
        { x: "education_level", y: "labor_primary", heat: 0.04 },
        { x: "education_level", y: "lasting_investment", heat: 0.0031 },
        { x: "education_level", y: "no_lasting_investmen", heat: 0.014 },
        { x: "education_level", y: "depressed", heat: -0.097 },
        { x: "total_members", y: "incoming_salary", heat: -0.042 },
        { x: "total_members", y: "incoming_own_farm", heat: 0.088 },
        { x: "total_members", y: "incoming_business", heat: 0.0033 },
        { x: "total_members", y: "incoming_no_business", heat: 0.063 },
        { x: "total_members", y: "incoming_agricultural", heat: 0.023 },
        { x: "total_members", y: "farm_expenses", heat: 0.071 },
        { x: "total_members", y: "labor_primary", heat: -0.04 },
        { x: "total_members", y: "lasting_investment", heat: 0.046 },
        { x: "total_members", y: "no_lasting_investmen", heat: 0.048 },
        { x: "total_members", y: "depressed", heat: 0.033 },
        { x: "gained_asset", y: "incoming_salary", heat: 0.031 },
        { x: "gained_asset", y: "incoming_own_farm", heat: 0.12 },
        { x: "gained_asset", y: "incoming_business", heat: 0.051 },
        { x: "gained_asset", y: "incoming_no_business", heat: 0.077 },
        { x: "gained_asset", y: "incoming_agricultural", heat: 0.029 },
        { x: "gained_asset", y: "farm_expenses", heat: 0.059 },
        { x: "gained_asset", y: "labor_primary", heat: 0.025 },
        { x: "gained_asset", y: "lasting_investment", heat: 0.032 },
        { x: "gained_asset", y: "no_lasting_investmen", heat: 0.031 },
        { x: "gained_asset", y: "depressed", heat: -0.0051 },
        { x: "durable_asset", y: "incoming_salary", heat: 0.075 },
        { x: "durable_asset", y: "incoming_own_farm", heat: 0.07 },
        { x: "durable_asset", y: "incoming_business", heat: 0.018 },
        { x: "durable_asset", y: "incoming_no_business", heat: 0.024 },
        { x: "durable_asset", y: "incoming_agricultural", heat: 0.026 },
        { x: "durable_asset", y: "farm_expenses", heat: 0.029 },
        { x: "durable_asset", y: "labor_primary", heat: 0.09 },
        { x: "durable_asset", y: "lasting_investment", heat: 0.25 },
        { x: "durable_asset", y: "no_lasting_investmen", heat: 0.022 },
        { x: "durable_asset", y: "depressed", heat: 0.038 },
        { x: "save_asset", y: "incoming_salary", heat: 0.044 },
        { x: "save_asset", y: "incoming_own_farm", heat: 0.039 },
        { x: "save_asset", y: "incoming_business", heat: 0.067 },
        { x: "save_asset", y: "incoming_no_business", heat: 0.054 },
        { x: "save_asset", y: "incoming_agricultural", heat: 0.023 },
        { x: "save_asset", y: "farm_expenses", heat: 0.04 },
        { x: "save_asset", y: "labor_primary", heat: 0.067 },
        { x: "save_asset", y: "lasting_investment", heat: 0.039 },
        { x: "save_asset", y: "no_lasting_investmen", heat: 0.029 },
        { x: "save_asset", y: "depressed", heat: 0.011 },
        { x: "living_expenses", y: "incoming_salary", heat: 0.086 },
        { x: "living_expenses", y: "incoming_own_farm", heat: 0.077 },
        { x: "living_expenses", y: "incoming_business", heat: 0.032 },
        { x: "living_expenses", y: "incoming_no_business", heat: 0.024 },
        { x: "living_expenses", y: "incoming_agricultural", heat: 0.12 },
        { x: "living_expenses", y: "farm_expenses", heat: 0.0035 },
        { x: "living_expenses", y: "labor_primary", heat: 0.08 },
        { x: "living_expenses", y: "lasting_investment", heat: 0.04 },
        { x: "living_expenses", y: "no_lasting_investmen", heat: 0.047 },
        { x: "living_expenses", y: "depressed", heat: -0.024 },
        { x: "other_expenses", y: "incoming_salary", heat: 0.043 },
        { x: "other_expenses", y: "incoming_own_farm", heat: 0.06 },
        { x: "other_expenses", y: "incoming_business", heat: 0.01 },
        { x: "other_expenses", y: "incoming_no_business", heat: 0.075 },
        { x: "other_expenses", y: "incoming_agricultural", heat: 0.073 },
        { x: "other_expenses", y: "farm_expenses", heat: 0.043 },
        { x: "other_expenses", y: "labor_primary", heat: 0.052 },
        { x: "other_expenses", y: "lasting_investment", heat: 0.047 },
        { x: "other_expenses", y: "no_lasting_investmen", heat: 0.019 },
        { x: "other_expenses", y: "depressed", heat: 0.011 },
        { x: "incoming_salary", y: "incoming_salary", heat: 1 },
        { x: "incoming_salary", y: "incoming_own_farm", heat: -0.27 },
        { x: "incoming_salary", y: "incoming_business", heat: -0.16 },
        { x: "incoming_salary", y: "incoming_no_business", heat: -0.074 },
        { x: "incoming_salary", y: "incoming_agricultural", heat: 0.019 },
        { x: "incoming_salary", y: "farm_expenses", heat: 0.023 },
        { x: "incoming_salary", y: "labor_primary", heat: 0.9 },
        { x: "incoming_salary", y: "lasting_investment", heat: 0.0085 },
        { x: "incoming_salary", y: "no_lasting_investmen", heat: 0.077 },
        { x: "incoming_salary", y: "depressed", heat: -0.0018 },
        { x: "incoming_own_farm", y: "incoming_salary", heat: -0.27 },
        { x: "incoming_own_farm", y: "incoming_own_farm", heat: 1 },
        { x: "incoming_own_farm", y: "incoming_business", heat: -0.2 },
        { x: "incoming_own_farm", y: "incoming_no_business", heat: 0.079 },
        { x: "incoming_own_farm", y: "incoming_agricultural", heat: 0.064 },
        { x: "incoming_own_farm", y: "farm_expenses", heat: 0.075 },
        { x: "incoming_own_farm", y: "labor_primary", heat: -0.3 },
        { x: "incoming_own_farm", y: "lasting_investment", heat: 0.085 },
        { x: "incoming_own_farm", y: "no_lasting_investmen", heat: 0.11 },
        { x: "incoming_own_farm", y: "depressed", heat: 0.01 },
        { x: "incoming_business", y: "incoming_salary", heat: -0.16 },
        { x: "incoming_business", y: "incoming_own_farm", heat: -0.2 },
        { x: "incoming_business", y: "incoming_business", heat: 1 },
        { x: "incoming_business", y: "incoming_no_business", heat: 0.53 },
        { x: "incoming_business", y: "incoming_agricultural", heat: 0.039 },
        { x: "incoming_business", y: "farm_expenses", heat: 0.061 },
        { x: "incoming_business", y: "labor_primary", heat: -0.18 },
        { x: "incoming_business", y: "lasting_investment", heat: 0.043 },
        { x: "incoming_business", y: "no_lasting_investmen", heat: -0.024 },
        { x: "incoming_business", y: "depressed", heat: -0.029 },
        { x: "incoming_no_business", y: "incoming_salary", heat: -0.074 },
        { x: "incoming_no_business", y: "incoming_own_farm", heat: 0.079 },
        { x: "incoming_no_business", y: "incoming_business", heat: 0.53 },
        { x: "incoming_no_business", y: "incoming_no_business", heat: 1 },
        { x: "incoming_no_business", y: "incoming_agricultural", heat: 0.086 },
        { x: "incoming_no_business", y: "farm_expenses", heat: 0.029 },
        { x: "incoming_no_business", y: "labor_primary", heat: -0.087 },
        { x: "incoming_no_business", y: "lasting_investment", heat: 0.058 },
        { x: "incoming_no_business", y: "no_lasting_investmen", heat: 0.0043 },
        { x: "incoming_no_business", y: "depressed", heat: -0.026 },
        { x: "incoming_agricultural", y: "incoming_salary", heat: 0.019 },
        { x: "incoming_agricultural", y: "incoming_own_farm", heat: 0.064 },
        { x: "incoming_agricultural", y: "incoming_business", heat: 0.039 },
        { x: "incoming_agricultural", y: "incoming_no_business", heat: 0.086 },
        { x: "incoming_agricultural", y: "incoming_agricultural", heat: 1 },
        { x: "incoming_agricultural", y: "farm_expenses", heat: 0.093 },
        { x: "incoming_agricultural", y: "labor_primary", heat: 0.042 },
        { x: "incoming_agricultural", y: "lasting_investment", heat: -0.0034 },
        { x: "incoming_agricultural", y: "no_lasting_investmen", heat: 0.067 },
        { x: "incoming_agricultural", y: "depressed", heat: -0.019 },
        { x: "farm_expenses", y: "incoming_salary", heat: 0.023 },
        { x: "farm_expenses", y: "incoming_own_farm", heat: 0.075 },
        { x: "farm_expenses", y: "incoming_business", heat: 0.061 },
        { x: "farm_expenses", y: "incoming_no_business", heat: 0.029 },
        { x: "farm_expenses", y: "incoming_agricultural", heat: 0.093 },
        { x: "farm_expenses", y: "farm_expenses", heat: 1 },
        { x: "farm_expenses", y: "labor_primary", heat: 0.026 },
        { x: "farm_expenses", y: "lasting_investment", heat: 0.0019 },
        { x: "farm_expenses", y: "no_lasting_investmen", heat: 0.13 },
        { x: "farm_expenses", y: "depressed", heat: -0.0051 },
        { x: "labor_primary", y: "incoming_salary", heat: 0.9 },
        { x: "labor_primary", y: "incoming_own_farm", heat: -0.3 },
        { x: "labor_primary", y: "incoming_business", heat: -0.18 },
        { x: "labor_primary", y: "incoming_no_business", heat: -0.087 },
        { x: "labor_primary", y: "incoming_agricultural", heat: 0.042 },
        { x: "labor_primary", y: "farm_expenses", heat: 0.026 },
        { x: "labor_primary", y: "labor_primary", heat: 1 },
        { x: "labor_primary", y: "lasting_investment", heat: 0.013 },
        { x: "labor_primary", y: "no_lasting_investmen", heat: 0.057 },
        { x: "labor_primary", y: "depressed", heat: -0.01 },
        { x: "lasting_investment", y: "incoming_salary", heat: 0.0085 },
        { x: "lasting_investment", y: "incoming_own_farm", heat: 0.085 },
        { x: "lasting_investment", y: "incoming_business", heat: 0.043 },
        { x: "lasting_investment", y: "incoming_no_business", heat: 0.058 },
        { x: "lasting_investment", y: "incoming_agricultural", heat: -0.0034 },
        { x: "lasting_investment", y: "farm_expenses", heat: -0.0019 },
        { x: "lasting_investment", y: "labor_primary", heat: 0.013 },
        { x: "lasting_investment", y: "lasting_investment", heat: 1 },
        { x: "lasting_investment", y: "no_lasting_investmen", heat: 0.043 },
        { x: "lasting_investment", y: "depressed", heat: 0.0045 },
        { x: "no_lasting_investmen", y: "incoming_salary", heat: 0.077 },
        { x: "no_lasting_investmen", y: "incoming_own_farm", heat: 0.11 },
        { x: "no_lasting_investmen", y: "incoming_business", heat: -0.024 },
        { x: "no_lasting_investmen", y: "incoming_no_business", heat: 0.0043 },
        { x: "no_lasting_investmen", y: "incoming_agricultural", heat: 0.067 },
        { x: "no_lasting_investmen", y: "farm_expenses", heat: 0.13 },
        { x: "no_lasting_investmen", y: "labor_primary", heat: 0.057 },
        { x: "no_lasting_investmen", y: "lasting_investment", heat: 0.043 },
        { x: "no_lasting_investmen", y: "no_lasting_investmen", heat: 1 },
        { x: "no_lasting_investmen", y: "depressed", heat: 0.052 },
        { x: "depressed", y: "incoming_salary", heat: -0.0016 },
        { x: "depressed", y: "incoming_own_farm", heat: 0.01 },
        { x: "depressed", y: "incoming_business", heat: -0.029 },
        { x: "depressed", y: "incoming_no_business", heat: -0.026 },
        { x: "depressed", y: "incoming_agricultural", heat: -0.019 },
        { x: "depressed", y: "farm_expenses", heat: -0.0051 },
        { x: "depressed", y: "labor_primary", heat: -0.01 },
        { x: "depressed", y: "lasting_investment", heat: 0.0045 },
        { x: "depressed", y: "no_lasting_investmen", heat: 0.052 },
        { x: "depressed", y: "depressed", heat: 1 },
    ];

    // create the chart and set the data
    chart = anychart.heatMap(data);

    var customColorScale = anychart.scales.linearColor();
    customColorScale.colors(["#C98A16", "#F8D9A0", "#96D0BD", "#5C9998", "#2C7877"]);

    chart.xAxis().overlapMode('allow-overlap');

    // set the color scale as the color scale of the chart
    chart.colorScale(customColorScale);

    // set the container id
    chart.container("container");

    chart.labels().enabled(true)

    // initiate drawing the chart
    chart.draw();

    // Get the x-axis object
    var xAxis = chart.xAxis();

    // Configure the rotation of the x-axis labels
    xAxis.labels().rotation(290);
    // Set the position of the x-axis labels to bottom
    // xAxis.labels().position("bottom");

  });
</script>

<style>
    #container {
      width: 100%;
      height: 8%;
      margin: 0;
      padding: 0;
    }
  </style>
